// ============================================
// SMART RIDE - EXPO CONFIG PLUGIN
// withProguardRules.js
// ============================================
// Writes a comprehensive proguard-rules.pro file into
// android/app/proguard-rules.pro during prebuild.
//
// Why: Even though withAbiSplits.js forces minifyEnabled false,
// R8 can still run in some edge cases (e.g. if a user manually
// edits build.gradle, or if a future Expo SDK changes defaults).
// When it does, these -dontwarn rules prevent the build from
// failing on "missing classes" referenced by expo-image-picker,
// @rnmapbox/maps, and other native modules.
// ============================================

const { withAppBuildGradle } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const PROGUARD_RULES = `# ============================================
# Smart Ride — ProGuard / R8 Rules (auto-generated by withProguardRules plugin)
# ============================================
# These rules tell R8 not to fail the build when it encounters
# "missing classes" referenced by Expo/React Native modules but
# not present on the compile classpath.
# ============================================

# ---- Expo Modules Kotlin (the #1 source of R8 failures) ----
-dontwarn expo.modules.kotlin.types.AnyTypeCache
-dontwarn expo.modules.kotlin.types.OptimizedRecord
-dontwarn expo.modules.kotlin.types.descriptors.RawTypeDescriptor
-dontwarn expo.modules.kotlin.types.descriptors.TypeDescriptor
-dontwarn expo.modules.kotlin.types.descriptors.TypeDescriptorKt
-dontwarn expo.modules.kotlin.types.descriptors.TypeDescriptorOfKt
-dontwarn expo.modules.kotlin.types.**

-keep class expo.modules.kotlin.** { *; }
-keep class expo.modules.** { *; }
-keepclassmembers class expo.modules.** { *; }

# ---- Mapbox (@rnmapbox/maps) ----
-keep class com.mapbox.** { *; }
-keep class com.rnmapbox.rnmbx.** { *; }
-dontwarn com.mapbox.**
-dontwarn com.rnmapbox.rnmbx.**

# ---- React Native core ----
-keep class com.facebook.react.** { *; }
-keep class com.facebook.hermes.** { *; }
-keep class com.swmansion.** { *; }
-dontwarn com.facebook.react.**

# ---- Google Sign-In ----
-keep class com.reactnativegooglesignin.** { *; }
-dontwarn com.reactnativegooglesignin.**

# ---- Google Play Services / Firebase ----
-keep class com.google.android.gms.** { *; }
-keep class com.google.firebase.** { *; }
-dontwarn com.google.android.gms.**
-dontwarn com.google.firebase.**

# ---- Agora (in-app calling) ----
-keep class io.agora.** { *; }
-dontwarn io.agora.**

# ---- Sentry ----
-keep class io.sentry.** { *; }
-dontwarn io.sentry.**

# ---- React Native Reanimated / Worklets ----
-keep class com.swmansion.reanimated.** { *; }
-keep class com.swmansion.worklets.** { *; }
-dontwarn com.swmansion.reanimated.**
-dontwarn com.swmansion.worklets.**

# ---- Generic Kotlin metadata ----
-keepattributes *Annotation*
-keepattributes Signature
-keepattributes SourceFile,LineNumberTable
-keepattributes InnerClasses
-keepattributes EnclosingMethod

# ---- Keep enum values ----
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

# ---- Keep native method declarations ----
-keepclasseswithmembernames class * {
    native <methods>;
}
`;

function withProguardRules(config) {
  return withAppBuildGradle(config, (config) => {
    try {
      const projectRoot = config.modRequest.projectRoot;
      const platformProjectPath = config.modRequest.platformProjectPath || 'android';
      const androidProjectPath = path.isAbsolute(platformProjectPath)
        ? platformProjectPath
        : path.join(projectRoot, platformProjectPath);
      const appDir = path.join(androidProjectPath, 'app');
      const proguardPath = path.join(appDir, 'proguard-rules.pro');

      if (!fs.existsSync(appDir)) {
        fs.mkdirSync(appDir, { recursive: true });
      }

      fs.writeFileSync(proguardPath, PROGUARD_RULES, 'utf8');
      console.log('[withProguardRules] Wrote proguard-rules.pro to', proguardPath);
    } catch (err) {
      console.warn('[withProguardRules] Failed to write proguard-rules.pro:', err.message);
    }
    return config;
  });
}

module.exports = withProguardRules;
