import { PrismaClient } from '@prisma/client';
const db = new PrismaClient();
const c = async (l: string, n: Promise<number>) => console.log(`  ${l.padEnd(42)} ${await n}`);
console.log('\n=== production state ===');
await c('users with @qa.invalid', db.user.count({ where: { email: { contains: '@qa.invalid' } } }));
await c('users with @smartride.test', db.user.count({ where: { email: { contains: '@smartride.test' } } }));
await c('orders (all)', db.order.count());
await c('orders with a task', db.task.count({ where: { orderId: { not: null } } }));
await c('tasks stuck in MATCHING/SEARCHING', db.task.count({ where: { status: { in: ['MATCHING','SEARCHING'] } } }));
await c('tasks not terminal', db.task.count({ where: { status: { notIn: ['COMPLETED','CANCELLED','FAILED','CLOSED','DELIVERED'] } } }));
await c('pending dispatch offers', db.dispatchMatch.count({ where: { status: 'PENDING' } }));
await c('riders online', db.rider.count({ where: { isOnline: true } }));
await c('riders holding a task', db.rider.count({ where: { currentTaskId: { not: null } } }));
await c('payments (all)', db.payment.count());
await c('payments PENDING/PROCESSING', db.payment.count({ where: { status: { in: ['PENDING','PROCESSING'] } } }));
await c('wallets with a balance', db.wallet.count({ where: { balance: { gt: 0 } } }));
await c('wallets with pendingBalance', db.wallet.count({ where: { pendingBalance: { gt: 0 } } }));
await c('provider orders', db.providerOrder.count());
await c('uncleared cash collections', db.cashCollection.count({ where: { status: 'COLLECTED' } }));
console.log();
await db.$disconnect();
